/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.12.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type Uint128 = string;
export interface InstantiateMsg {
  dues: MemberBalanceUnchecked[];
  is_enrollment: boolean;
}
export interface MemberBalanceUnchecked {
  addr: string;
  cw20?: Cw20Coin[];
  cw721?: Cw721Collection[];
  native?: Coin[];
}
export interface Cw20Coin {
  address: string;
  amount: Uint128;
}
export interface Cw721Collection {
  address: string;
  token_ids: string[];
}
export interface Coin {
  amount: Uint128;
  denom: string;
}
export type ExecuteMsg = {
  withdraw: {
    cw20_msg?: Binary | null;
    cw721_msg?: Binary | null;
  };
} | {
  enrollment_withdraw: {
    addrs: string[];
    entry_fee: Coin;
  };
} | {
  receive_native: {};
} | {
  receive: Cw20ReceiveMsg;
} | {
  receive_nft: Cw721ReceiveMsg;
} | {
  distribute: {
    activation_height?: number | null;
    distribution?: DistributionForString | null;
    group_contract: string;
    layered_fees?: FeeInformationForString[] | null;
  };
} | {
  lock: {
    transfer_ownership?: TransferEscrowOwnershipMsg | null;
    value: boolean;
  };
} | {
  claw: {};
} | {
  update_ownership: Action;
};
export type Binary = string;
export type Decimal = string;
export type Action = {
  transfer_ownership: {
    expiry?: Expiration | null;
    new_owner: string;
  };
} | "accept_ownership" | "renounce_ownership";
export type Expiration = {
  at_height: number;
} | {
  at_time: Timestamp;
} | {
  never: {};
};
export type Timestamp = Uint64;
export type Uint64 = string;
export interface Cw20ReceiveMsg {
  amount: Uint128;
  msg: Binary;
  sender: string;
}
export interface Cw721ReceiveMsg {
  msg: Binary;
  sender: string;
  token_id: string;
}
export interface DistributionForString {
  member_percentages: MemberPercentageForString[];
  remainder_addr: string;
}
export interface MemberPercentageForString {
  addr: string;
  percentage: Decimal;
}
export interface FeeInformationForString {
  cw20_msg?: Binary | null;
  cw721_msg?: Binary | null;
  receiver: string;
  tax: Decimal;
}
export interface TransferEscrowOwnershipMsg {
  addr: string;
  is_enrollment: boolean;
}
export type QueryMsg = {
  balances: {
    limit?: number | null;
    start_after?: string | null;
  };
} | {
  balance: {
    addr: string;
  };
} | {
  due: {
    addr: string;
  };
} | {
  dues: {
    limit?: number | null;
    start_after?: string | null;
  };
} | {
  initial_dues: {
    limit?: number | null;
    start_after?: string | null;
  };
} | {
  is_funded: {
    addr: string;
  };
} | {
  is_fully_funded: {};
} | {
  total_balance: {};
} | {
  is_locked: {};
} | {
  dump_state: {
    addr?: string | null;
  };
} | {
  ownership: {};
};
export type MigrateMsg = {
  from_compatible: {};
};
export interface BalanceVerified {
  cw20?: {};
  cw721?: {};
  native?: {};
}
export type Addr = string;
export type ArrayOfMemberBalanceChecked = MemberBalanceChecked[];
export interface MemberBalanceChecked {
  addr: Addr;
  balance: BalanceVerified;
}
export interface DumpStateResponse {
  balance: BalanceVerified;
  due: BalanceVerified;
  is_locked: boolean;
  total_balance: BalanceVerified;
}
export type Boolean = boolean;
export interface OwnershipForString {
  owner?: string | null;
  pending_expiry?: Expiration | null;
  pending_owner?: string | null;
}