/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.12.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export interface InstantiateMsg {
  owner: string;
}
export type ExecuteMsg = {
  create_entry: {
    category_id?: Uint128 | null;
    dao_config: TeamDaoConfig;
    description: string;
    title: string;
  };
} | {
  update_entry_status: {
    entry_id: number;
    status: EntryStatus;
  };
} | {
  apply: {
    entry_id: number;
  };
} | {
  withdraw_application: {
    entry_id: number;
  };
} | {
  update_applicant_status: {
    applicant: string;
    entry_id: number;
    status: ApplicantStatus;
  };
} | {
  update_ownership: Action;
};
export type Uint128 = string;
export type Duration = {
  height: number;
} | {
  time: number;
};
export type Threshold = {
  absolute_percentage: {
    percentage: PercentageThreshold;
  };
} | {
  threshold_quorum: {
    quorum: PercentageThreshold;
    threshold: PercentageThreshold;
  };
} | {
  absolute_count: {
    threshold: Uint128;
  };
};
export type PercentageThreshold = {
  majority: {};
} | {
  percent: Decimal;
};
export type Decimal = string;
export type EntryStatus = "open" | "created" | "closed" | "aborted";
export type ApplicantStatus = ("default" | "approved") | {
  rejected: {
    reason: string;
  };
};
export type Action = {
  transfer_ownership: {
    expiry?: Expiration | null;
    new_owner: string;
  };
} | "accept_ownership" | "renounce_ownership";
export type Expiration = {
  at_height: number;
} | {
  at_time: Timestamp;
} | {
  never: {};
};
export type Timestamp = Uint64;
export type Uint64 = string;
export interface TeamDaoConfig {
  cw4_group_code_id: number;
  cw4_voting_code_id: number;
  dao_code_id: number;
  dao_description?: string;
  dao_name?: string;
  image_url?: string | null;
  max_voting_period: Duration;
  prepropose_single_code_id: number;
  proposal_single_code_id: number;
  threshold: Threshold;
}
export type QueryMsg = {
  get_entry: {
    entry_id: number;
  };
} | {
  list_entries: {
    category_status?: CategoryStatusMsg | null;
    limit?: number | null;
    start_after?: number | null;
  };
} | {
  get_applicant: {
    applicant: string;
    entry_id: number;
  };
} | {
  list_applicants: {
    entry_id: number;
    limit?: number | null;
    start_after?: string | null;
    status?: ApplicantStatus | null;
  };
} | {
  list_teams: {
    limit?: number | null;
    start_after?: string | null;
    user: string;
  };
} | {
  ownership: {};
};
export interface CategoryStatusMsg {
  category_id?: Uint128 | null;
  status: EntryStatus;
}
export type Addr = string;
export interface ApplicantResponse {
  applicant: Addr;
  status: ApplicantStatus;
}
export interface TeamEntryResponse {
  approved_applicants_count: number;
  category_id?: Uint128 | null;
  created_at: Timestamp;
  creator: Addr;
  dao_config: TeamDaoConfig;
  description: string;
  entry_id: number;
  pending_applicants_count: number;
  rejected_applicants_count: number;
  status: EntryStatus;
  title: string;
}
export type ArrayOfApplicantResponse = ApplicantResponse[];
export type ArrayOfTeamEntryResponse = TeamEntryResponse[];
export type ArrayOfAddr = Addr[];
export interface OwnershipForString {
  owner?: string | null;
  pending_expiry?: Expiration | null;
  pending_owner?: string | null;
}