/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.12.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type Decimal = string;
export interface InstantiateMsg {
  config: VestingConfiguration;
  owner: string;
}
export interface VestingConfiguration {
  denom: string;
  upfront_ratio: Decimal;
  vesting_time: number;
}
export type ExecuteMsg = {
  apply: ApplyMsg;
} | {
  update: {
    application_id: Uint128;
    application_info: ApplyMsg;
  };
} | {
  withdraw: {
    application_id: Uint128;
  };
} | {
  accept_application: {
    application_id: Uint128;
  };
} | {
  reject_application: {
    application_id: Uint128;
    reason?: string | null;
  };
} | {
  update_vesting_configuration: {
    config: VestingConfiguration;
  };
} | {
  update_ownership: Action;
};
export type Uint128 = string;
export type Action = {
  transfer_ownership: {
    expiry?: Expiration | null;
    new_owner: string;
  };
} | "accept_ownership" | "renounce_ownership";
export type Expiration = {
  at_height: number;
} | {
  at_time: Timestamp;
} | {
  never: {};
};
export type Timestamp = Uint64;
export type Uint64 = string;
export interface ApplyMsg {
  description: string;
  project_links: ProjectLink[];
  requested_amount: Uint128;
  title: string;
}
export interface ProjectLink {
  title: string;
  url: string;
}
export type QueryMsg = {
  vesting_configuration: {};
} | {
  application: {
    application_id: Uint128;
  };
} | {
  applications: {
    filter?: ApplicationsFilter | null;
    limit?: number | null;
    start_after?: Uint128 | null;
  };
} | {
  payroll_address: {};
} | {
  ownership: {};
};
export type ApplicationsFilter = {
  status: ApplicationStatus;
} | {
  applicant: string;
};
export type ApplicationStatus = {
  pending: {};
} | {
  accepted: {};
} | {
  rejected: {
    reason?: string | null;
  };
};
export type MigrateMsg = {
  from_compatible: {};
};
export type Addr = string;
export interface ApplicationResponse {
  application: ApplicationInfo;
  application_id: Uint128;
}
export interface ApplicationInfo {
  applicant: Addr;
  description: string;
  project_links: ProjectLink[];
  requested_amount: Uint128;
  status: ApplicationStatus;
  title: string;
}
export type ArrayOfApplicationResponse = ApplicationResponse[];
export interface OwnershipForString {
  owner?: string | null;
  pending_expiry?: Expiration | null;
  pending_owner?: string | null;
}