/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _0 from "./ArenaWagerModule.types";
import * as _1 from "./ArenaWagerModule.client";
import * as _2 from "./ArenaWagerModule.react-query";
import * as _3 from "./ArenaLeagueModule.types";
import * as _4 from "./ArenaLeagueModule.client";
import * as _5 from "./ArenaLeagueModule.react-query";
import * as _6 from "./ArenaEscrow.types";
import * as _7 from "./ArenaEscrow.client";
import * as _8 from "./ArenaEscrow.react-query";
import * as _9 from "./ArenaCore.types";
import * as _10 from "./ArenaCore.client";
import * as _11 from "./ArenaCore.react-query";
import * as _12 from "./Cw721Base.types";
import * as _13 from "./Cw721Base.client";
import * as _14 from "./Cw721Base.react-query";
import * as _15 from "./Cw20Base.types";
import * as _16 from "./Cw20Base.client";
import * as _17 from "./Cw20Base.react-query";
import * as _18 from "./DaoDaoCore.types";
import * as _19 from "./DaoDaoCore.client";
import * as _20 from "./DaoDaoCore.react-query";
import * as _21 from "./DaoVotingTokenStaked.types";
import * as _22 from "./DaoVotingTokenStaked.client";
import * as _23 from "./DaoVotingTokenStaked.react-query";
import * as _24 from "./DaoVotingCw721Staked.types";
import * as _25 from "./DaoVotingCw721Staked.client";
import * as _26 from "./DaoVotingCw721Staked.react-query";
import * as _27 from "./DaoVotingCw721Roles.types";
import * as _28 from "./DaoVotingCw721Roles.client";
import * as _29 from "./DaoVotingCw721Roles.react-query";
import * as _30 from "./DaoVotingCw20Staked.types";
import * as _31 from "./DaoVotingCw20Staked.client";
import * as _32 from "./DaoVotingCw20Staked.react-query";
import * as _33 from "./DaoVotingCw4.types";
import * as _34 from "./DaoVotingCw4.client";
import * as _35 from "./DaoVotingCw4.react-query";
import * as _36 from "./DaoProposalSingle.types";
import * as _37 from "./DaoProposalSingle.client";
import * as _38 from "./DaoProposalSingle.react-query";
import * as _39 from "./DaoProposalMultiple.types";
import * as _40 from "./DaoProposalMultiple.client";
import * as _41 from "./DaoProposalMultiple.react-query";
import * as _42 from "./DaoProposalCondorcet.types";
import * as _43 from "./DaoProposalCondorcet.client";
import * as _44 from "./DaoProposalCondorcet.react-query";
export namespace contracts {
  export const ArenaWagerModule = { ..._0,
    ..._1,
    ..._2
  };
  export const ArenaLeagueModule = { ..._3,
    ..._4,
    ..._5
  };
  export const ArenaEscrow = { ..._6,
    ..._7,
    ..._8
  };
  export const ArenaCore = { ..._9,
    ..._10,
    ..._11
  };
  export const Cw721Base = { ..._12,
    ..._13,
    ..._14
  };
  export const Cw20Base = { ..._15,
    ..._16,
    ..._17
  };
  export const DaoDaoCore = { ..._18,
    ..._19,
    ..._20
  };
  export const DaoVotingTokenStaked = { ..._21,
    ..._22,
    ..._23
  };
  export const DaoVotingCw721Staked = { ..._24,
    ..._25,
    ..._26
  };
  export const DaoVotingCw721Roles = { ..._27,
    ..._28,
    ..._29
  };
  export const DaoVotingCw20Staked = { ..._30,
    ..._31,
    ..._32
  };
  export const DaoVotingCw4 = { ..._33,
    ..._34,
    ..._35
  };
  export const DaoProposalSingle = { ..._36,
    ..._37,
    ..._38
  };
  export const DaoProposalMultiple = { ..._39,
    ..._40,
    ..._41
  };
  export const DaoProposalCondorcet = { ..._42,
    ..._43,
    ..._44
  };
}