/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.23.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type Binary = string;
export interface InstantiateMsg {
  competition_modules_instantiate_info: ModuleInstantiateInfo[];
}
export interface ModuleInstantiateInfo {
  code_id: number;
  label: string;
  msg: Binary;
}
export type ExecuteMsg = {
  update_competition_modules: {
    to_add: ModuleInstantiateInfo[];
    to_disable: string[];
  };
} | {
  update_admin: {
    admin?: string | null;
  };
} | {
  update_record: {
    msg: Binary;
    token: string;
  };
};
export type QueryMsg = {
  competition_modules: {
    limit?: number | null;
    start_after?: string | null;
  };
} | {
  user_record: {
    addr: string;
  };
} | {
  admin: {};
} | {
  dump_state: {
    addr: string;
  };
};
export interface MigrateMsg {}
export interface AdminResponse {
  admin?: string | null;
}
export type Addr = string;
export interface CompetitionModulesResponse {
  competition_modules: CompetitionModuleResponse[];
}
export interface CompetitionModuleResponse {
  addr: Addr;
  description?: string | null;
  name: string;
}
export type Uint128 = string;
export interface DumpStateResponse {
  competition_modules: CompetitionModulesResponse;
  record: UserRecordResponse;
}
export interface UserRecordResponse {
  draws: Uint128;
  losses: Uint128;
  wins: Uint128;
}