/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.23.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type Addr = string;
export type Uint128 = string;
export type GenericTokenType = "native" | "cw20" | "cw721";
export interface InstantiateMsg {
  due: MemberBalance[];
}
export interface MemberBalance {
  balances: GenericTokenBalance[];
  member: string;
}
export interface GenericTokenBalance {
  addr?: Addr | null;
  amount: Uint128;
  denom?: string | null;
  token_type: GenericTokenType;
}
export type ExecuteMsg = {
  refund: {};
} | {
  receive_native: {};
} | {
  receive: Cw20ReceiveMsg;
} | {
  receive_nft: Cw721ReceiveMsg;
} | {
  handle_competition_result: CwCompetitionResultMsg;
} | {
  handle_competition_state_changed: CwCompetitionStateChangedMsg;
};
export type Binary = string;
export type CompetitionState = "pending" | "staged" | "active" | "inactive";
export interface Cw20ReceiveMsg {
  amount: Uint128;
  msg: Binary;
  sender: string;
}
export interface Cw721ReceiveMsg {
  msg: Binary;
  sender: string;
  token_id: string;
}
export interface CwCompetitionResultMsg {
  distribution?: MemberShare[] | null;
}
export interface MemberShare {
  addr: string;
  shares: number;
}
export interface CwCompetitionStateChangedMsg {
  new_state: CompetitionState;
  old_state: CompetitionState;
}
export type QueryMsg = {
  admin: {};
} | {
  balance: {
    member: string;
  };
} | {
  due: {
    member: string;
  };
} | {
  total: {};
};
export interface MigrateMsg {}
export interface AdminResponse {
  admin?: string | null;
}
export type ArrayOfGenericTokenBalance = GenericTokenBalance[];