/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.23.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _0 from "./AgonCore.types";
import * as _1 from "./AgonCore.client";
import * as _2 from "./AgonEscrow.types";
import * as _3 from "./AgonEscrow.client";
import * as _4 from "./Cw4Disbursement.types";
import * as _5 from "./Cw4Disbursement.client";
import * as _6 from "./DaoCore.types";
import * as _7 from "./DaoCore.client";
import * as _8 from "./CwAdminFactory.types";
import * as _9 from "./CwAdminFactory.client";
import * as _10 from "./CwTokenSwap.types";
import * as _11 from "./CwTokenSwap.client";
import * as _12 from "./DaoPreProposeApprovalSingle.types";
import * as _13 from "./DaoPreProposeApprovalSingle.client";
import * as _14 from "./DaoPreProposeApprover.types";
import * as _15 from "./DaoPreProposeApprover.client";
import * as _16 from "./DaoPreProposeMultiple.types";
import * as _17 from "./DaoPreProposeMultiple.client";
import * as _18 from "./DaoPreProposeSingle.types";
import * as _19 from "./DaoPreProposeSingle.client";
import * as _20 from "./DaoProposalMultiple.types";
import * as _21 from "./DaoProposalMultiple.client";
import * as _22 from "./DaoProposalSingle.types";
import * as _23 from "./DaoProposalSingle.client";
import * as _24 from "./Cw20StakeExternalRewards.types";
import * as _25 from "./Cw20StakeExternalRewards.client";
import * as _26 from "./Cw20StakeRewardDistributor.types";
import * as _27 from "./Cw20StakeRewardDistributor.client";
import * as _28 from "./Cw20Stake.types";
import * as _29 from "./Cw20Stake.client";
import * as _30 from "./DaoVotingCw20Staked.types";
import * as _31 from "./DaoVotingCw20Staked.client";
import * as _32 from "./DaoVotingCw4.types";
import * as _33 from "./DaoVotingCw4.client";
import * as _34 from "./DaoVotingCw721Staked.types";
import * as _35 from "./DaoVotingCw721Staked.client";
import * as _36 from "./DaoVotingNativeStaked.types";
import * as _37 from "./DaoVotingNativeStaked.client";
export namespace contracts {
  export const AgonCore = { ..._0,
    ..._1
  };
  export const AgonEscrow = { ..._2,
    ..._3
  };
  export const Cw4Disbursement = { ..._4,
    ..._5
  };
  export const DaoCore = { ..._6,
    ..._7
  };
  export const CwAdminFactory = { ..._8,
    ..._9
  };
  export const CwTokenSwap = { ..._10,
    ..._11
  };
  export const DaoPreProposeApprovalSingle = { ..._12,
    ..._13
  };
  export const DaoPreProposeApprover = { ..._14,
    ..._15
  };
  export const DaoPreProposeMultiple = { ..._16,
    ..._17
  };
  export const DaoPreProposeSingle = { ..._18,
    ..._19
  };
  export const DaoProposalMultiple = { ..._20,
    ..._21
  };
  export const DaoProposalSingle = { ..._22,
    ..._23
  };
  export const Cw20StakeExternalRewards = { ..._24,
    ..._25
  };
  export const Cw20StakeRewardDistributor = { ..._26,
    ..._27
  };
  export const Cw20Stake = { ..._28,
    ..._29
  };
  export const DaoVotingCw20Staked = { ..._30,
    ..._31
  };
  export const DaoVotingCw4 = { ..._32,
    ..._33
  };
  export const DaoVotingCw721Staked = { ..._34,
    ..._35
  };
  export const DaoVotingNativeStaked = { ..._36,
    ..._37
  };
}